### ISSUE TITLE
Would it be possible for this to be making an infusion recipe just not work?

### ISSUE THREAD

**Issue by Azutte** [SpitefulFox/Unthaumic#2]
Trying to make the "Ring of the Covetous Coin" from Witching Gadgets, and I've triple-checked all the items (and respective metadata), and I've re-placed all my altar's blocks. Doesn't work!

 Just checking all the avenues, here -- is it possible that I don't "actually" have the recipe, that it just looks like I do?

**Comment by SpitefulFox** [comment]
No.
